# Generated by Django 6.0.2 on 2026-02-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
    ]
