# Generated by Django 5.0.6 on 2024-05-17 10:59

import cmp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="soldierdeath",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=cmp.models.get_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="decoration",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="powcamp",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="soldierdecoration",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="soldierimprisonment",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="ProvostAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(default="")),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provostappointments",
                        to="cmp.rank",
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cmp.soldier"
                    ),
                ),
            ],
        ),
    ]
