# Generated by Django 5.1.6 on 2025-02-21 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmp", "0002_soldierdeath_image_alter_company_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True, max_length=50000)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name="soldier",
            options={"ordering": ["surname", "initials"]},
        ),
        migrations.AddField(
            model_name="soldier",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="soldier",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="soldier",
            name="provost_officer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cemetery",
            name="latitude",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="cemetery",
            name="longitude",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="country",
            name="alpha2",
            field=models.CharField(blank=True, default="", max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="alpha3",
            field=models.CharField(blank=True, default="", max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="decoration",
            name="abbreviation",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="decoration",
            name="details_link",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="decoration",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="powcamp",
            name="latitude",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="powcamp",
            name="longitude",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="powcamp",
            name="nearest_city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="powcamp",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="powcamp",
            name="wartime_country",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="army_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="initials",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="soldierdeath",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="cmp.company",
            ),
        ),
        migrations.AlterField(
            model_name="soldierimprisonment",
            name="legacy_company",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="soldierimprisonment",
            name="legacy_date_from",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="soldierimprisonment",
            name="legacy_date_to",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="soldierimprisonment",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="soldierimprisonment",
            name="pow_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
