name: cmp-django-base-build
env:
  SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

permissions:
  pull-requests: write

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]
    pull_request:
        branches: [main]

strategy:
  matrix:
    python-version: [ 3.11 ]        

jobs:
  core_base_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CMP code
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
      - name Install requirements  
        run: |
            pip install -r requirements.txt
      - name: Make Migrations
        run: |
            python manage.py makemigrations
      - name: Migrations
        run: |
            python manage.py migrate
      - name: Collectstatic
        run: |
            python manage.py collectstatic
      - name: Run tests
        run: |
            python manage.py test
      - name: Run test with coverage report
        run: |
            pytest
      - name: Coveralls Coverage Report
        uses: coverallsapp/github-action@v2.2.3    
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
        if: needs.pr-check.outputs.number != 'null'
      - name: Artifact Upload coverage report
        uses: actions/upload-artifact@v3
        with:
            name: coverage-report
            path: |
              coverage.xml

